namespace Minsk.CodeAnalysis.Syntax
{
    public enum SyntaxKind
    {
        // Tokens
        BadToken,
        EndOfFileToken,
        WhiteSpaceToken,
        NumberToken,
        StringToken,
        PlusToken,
        MinusToken,
        StarToken,
        SlashToken,
        BangToken,
        EqualsToken,
        OpenParenthesisToken,
        CloseParenthesisToken,
        OpenBraceToken,
        CloseBraceToken,
        ColonToken,
        IdentifierToken,
        TildeToken,
        PipeToken,
        PipePipeToken,
        AmpersandToken,
        AmpersandAmpersandToken,
        HatToken,
        EqualsEqualsToken,
        LessToken,
        LessOrEqualsToken,
        GreaterToken,
        GraterOrEqualsToken,
        BangEqualsToken,
        CommaToken,

        // Keywords
        ElseKeyword,
        FalseKeyword,
        ForKeyword,
        FunctionKeyword,
        IfKeyword,
        LetKeyword,
        ToKeyword,
        TrueKeyword,
        VarKeyword,
        WhileKeyword,
        DoKeyword,
        ContinueKeyword,
        BreakKeyword,

        // Nodes
        CompilationUnit,
        GlobalStatement,
        FunctionDeclaration,
        Parameter,
        ElseClause,
        TypeClause,

        // Statements
        BlockStatement,
        ExpressionStatement,
        ContinueStatement,
        BreakStatement,
        ForStatement,
        IfStatement,
        VariableDeclaration,
        WhileStatement,
        DoWhileStatement,

        // Expressions
        LiteralExpression,
        NameExpression,
        UnaryExpression,
        BinaryExpression,
        ParenthesizedExpression,
        AssignmentExpression,
        CallExpression,
    }
}
